version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker/development/nginx
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - frontend
            - api

    frontend:
        build:
            context: frontend/docker/development/nginx
        depends_on:
            - frontend-node

    frontend-node:
        build:
            context: frontend/docker/development/node
        volumes:
            - ./frontend:/app
        command: yarn start
        tty: true

    frontend-node-cli:
        build:
            context: frontend/docker/development/node
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker/development/nginx
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm

    api-php-fpm:
        build:
            context: api/docker/development/php-fpm
        env_file: .env
        environment:
            PHP_IDE_CONFIG: serverName=API
        volumes:
            - ./api:/app

    api-php-cli:
        build:
            context: api/docker/development/php-cli
        env_file: .env
        volumes:
            - ./api:/app

    api-postgres:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    api-postgres:
